spring:
  data:
    mongodb:
      username: gabriel
      password: gabriel
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: paymentGroup,orderGroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringSerializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:

        spring.json.type.mapping: orderConfirmation:com.gabriel.ecommerce.kafka.OrderConfirmation,paymentConfirmation:com.gabriel.ecommerce.notification.PaymentNotificationRequest
  application:
    name: notification-service
