spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:9098/realms/micro-services"
  config:
    import: "optional:configserver:http://host.docker.internal:8888/"
  application:
    name: gateway-service
